MVI H,00H
MVI C,64H ;; C <= 100 MS
;; OF DELAY
LOAD:
LDA 2000H ;; READ DATA
;; FROM SWITCHES
MOV D,A ;; COPY DATA TO D
ANI 0FH ;; A && 0000 1111
;; AKA TRAP THE 4 LSBs
MOV E,A ;; SAVE TO E
;; E HOLDS THE TIME
MOV A,D ;; RESTORE READ DATA
ANI F0H ;; A && 1111 0000
;; TRAP THE 4 MSBs
;; BY AND-ING
RRC ;; RO
RRC ;; TA
RRC ;; TE
RRC ;; (OR SHIFT) RIGHT-WISE
;; THE ACCUMULATOR
MOV L,A ;; L: BLINKS REGISTER
INR E ;; INCREMENT E
;; SINCE TOTAL BLINK
;; TIME = X + 1
FLASH:
MVI D,00H
CALL LIGHT ;; LEDS ON ROUTINE
CALL DELB1 ;; DELAY ROUTINE
CALL OFF ;; LEDS OFF ROUTINE
MVI D,00H
CALL DELB1 ;; DELAY ROUTINE
INR H ;; INCREMENT H UNTIL
;; IT'S EQUAL TO L
;; THEN WE NOW THAT
;; OUR LEDS BLINKED
;; FOR Y + 1 TIMES
MOV A,H ;; PASS TO A
CMP L ;; COMPARE WITH L
JZ END ;; END IT, IF REACHED
;; NUMBER OF BLINKS
JMP LOAD ;; START OVER
OFF:
MVI A,FFH ;; SHUTDOWN THE LEDS
STA 3000H
RET
LIGHT:
MVI A,00H ;; TURN ON THE LEDS
STA 3000H
RET
DELB1:
CALL DELB ;; HERE WE HAVE OUR
;; INITIAL DELAY
;; MULTIPLIED BY
;; THE INPUT + 1
INR D ;; INCREMENT D UNTIL
;; IS EQUAL TO E
MOV A,D
CMP E
JC DELB1
RET
END:
HLT
END
