IN 10H
CALL SHUTDOWN
PUSH PSW ;; SAVE AND RESTORE CONTENT
PUSH B ;; OF REGISTERS
PUSH D
PUSH H
CALL STDM ;; SHUTDOWN DISPLAYS
POP H
POP D
POP B
POP PSW
MAIN:
CALL GET_NUMBER
GET_NUMBER:
CALL KIND ;; GET NUMBER FROM USER
MOV B,A ;; SAVE NUMBER
RAR ;; RO
RAR ;; TA
RAR ;; TE
RAR ;; RIGHTWISE, NOW 4 MSBs ARE
;; @ LSB LOCATIONS
ANI 0FH ;; ISOLATE THEM
LXI H,0B01H ;; LOAD MEMORY LOCATION 0B01H
MOV M,A ;; STORE CONTENT OF A @ 0B01H
MOV A,B ;; RESTORE A
ANI 0FH ;; ISOLATE REAL LSBs
DCX H ;; GO TO MEMORY LOCATION 0B00H
MOV M,A ;; MOVE CONTENT THERE
LXI D,0B00H ;; LOAD STARTING ADDRESS
;; FROM WHERE ON WE WANT
;; TO PRINT STORED CONTENT
CALL STDM ;; PRINT
CALL DCD
RET
SHUTDOWN: ;; SHUTDOWN EVERYTING BLOD
MVI A,00H ;; CLEAR A
LXI B,0000H ;; CLEAR B-C
LXI D,0B00H ;; SET ADDRESS FROM
;; WHERE AND ON WE
;; WANT TO PRINT
;; CONTENT STORED
LXI H,0B00H ;; SET MEMORY
;; LOCATION @ 0B00H
MVI M,10H ;; LOAD 6 CONTINUOUS
;; MEMORY LOCATIONS
;; WITH 10H == VOID
;; IN ORDER TO SHUTDOWN
;; ALL 6 DISPLAYS
INX H
MVI M,10H
INX H
MVI M,10H
INX H
MVI M,10H
INX H
MVI M,10H
INX H
MVI M,10H
RET
END
